services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express:latest
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root  # Correction ici (pas de sous-section [2])
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongodb
    ports:
      - "8081:8081"

  backend:
    build: ./backend
    env_file: .env  # Référence au fichier .env
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

volumes:
  mongodb_data: