services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongo-network

  mongoexpress:
    image: mongo-express:latest
    container_name: mongoexpress
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
    networks:
      - mongo-network

  binance-backend:
    build:
      context: ../Binance/backend
      dockerfile: Dockerfile
    container_name: binance-backend
    ports:
      - "5000:5000"
    volumes:
      - ../Binance/backend:/app
    networks:
      - binance-network
    depends_on:
      - mongodb

  binance-frontend:
    build:
      context: ../Binance/frontend
      dockerfile: Dockerfile
    container_name: binance-frontend
    ports:
      - "3000:3000"
    volumes:
      - ../Binance/frontend:/app
    command: ["npm", "start"]
    networks:
      - binance-network
    depends_on:
      - binance-backend

networks:
  mongo-network:
  binance-network:

volumes:
  mongodb_data: