FROM mongo-express:latest

ENV ME_CONFIG_MONGODB_SERVER=mongodb
ENV ME_CONFIG_MONGODB_PORT=27017
ENV ME_CONFIG_BASICAUTH_USERNAME=admin
ENV ME_CONFIG_BASICAUTH_PASSWORD=pass

EXPOSE 8081

CMD ["npm", "start"]