services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongo-network

  mongoexpress:
    image: mongo-express:latest
    container_name: mongoexpress
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
    networks:
      - mongo-network

  web:
    build: 
      context: ./Binance/backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_API_SECRET=${BINANCE_API_SECRET}

    networks:
      - mongo-network
    depends_on:
      - mongodb


  



networks:
  mongo-network:
 
volumes:
  mongodb_data: